### ISSUE TITLE
Unable to run medium-importer

### ISSUE THREAD

**Issue by slavakurilyak** [stackbithq/stackbit-medium-importer#2]
The command `medium-importer` does not seem to work.

Steps to replicate the issue: 

1. Install stackbit-medium-importer using `$ npm install @stackbit/stackbit-medium-importer`
2. Run stackbit-medium-importer using `$ medium-importer`
3. See error below:

```
zsh: command not found: medium-importer
```

**Comment by davbree** [comment]
Please try `./node_modules/.bin/medium-importer` or install it globally using `npm install -g  @stackbit/stackbit-medium-importer`
